# Example configuration for Redis cache support in Firefly Common Domain Library
# 
# This configuration shows how to enable Redis caching for CQRS queries.
# Redis cache is DISABLED by default and will not attempt connections unless explicitly enabled.

firefly:
  cqrs:
    enabled: true
    query:
      # Enable query caching (default: true)
      caching-enabled: true
      
      # Default cache TTL for queries (default: 15 minutes)
      cache-ttl: 15m
      
      # Cache configuration
      cache:
        # Cache type: LOCAL (default) or REDIS
        type: REDIS
        
        # Redis cache configuration
        redis:
          # Enable Redis cache (default: false)
          # When false, no Redis connection will be attempted
          enabled: true
          
          # Redis connection settings
          host: localhost
          port: 6379
          database: 0
          
          # Optional password
          # password: your-redis-password
          
          # Connection timeout (default: 2 seconds)
          timeout: 2s
          
          # Key prefix for cache entries (default: "firefly:cqrs:")
          key-prefix: "firefly:cqrs:"
          
          # Enable cache statistics (default: true, reserved for future use)
          statistics: true

---
# Alternative: Use local cache (default behavior)
spring:
  config:
    activate:
      on-profile: local-cache

firefly:
  cqrs:
    enabled: true
    query:
      caching-enabled: true
      cache-ttl: 15m
      cache:
        # Use local in-memory cache (default)
        type: LOCAL
        redis:
          # Redis is disabled by default - no connection attempts
          enabled: false

---
# Production Redis configuration example
spring:
  config:
    activate:
      on-profile: production-redis

firefly:
  cqrs:
    enabled: true
    query:
      caching-enabled: true
      cache-ttl: 30m  # Longer TTL for production
      cache:
        type: REDIS
        redis:
          enabled: true
          host: redis-cluster.production.local
          port: 6379
          database: 1
          password: ${REDIS_PASSWORD}
          timeout: 5s
          key-prefix: "banking:cqrs:"
          statistics: true      # Reserved for future use

# Note: When Redis is enabled, ensure Redis server is available
# When Redis is disabled (default), the framework uses local in-memory cache
# No Redis dependencies are required when using local cache only
